"""init tables

Revision ID: 0693326c310b
Revises: 
Create Date: 2025-11-16 18:48:05.641833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0693326c310b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_file',
    sa.Column('case_file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('login_info_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('case_file_id'),
    schema='qa_test'
    )
    op.create_table('case_sheet',
    sa.Column('case_sheet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('case_sheet_id'),
    schema='qa_test'
    )
    op.create_table('generated_script',
    sa.Column('generated_script_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_step_id', sa.Integer(), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('generated_script_id'),
    sa.UniqueConstraint('sub_step_id'),
    schema='qa_test'
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    schema='qa_test'
    )
    op.create_table('step',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('step_id'),
    schema='qa_test'
    )
    op.create_table('sub_step',
    sa.Column('sub_step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('sub_step_order', sa.Integer(), nullable=False),
    sa.Column('sub_step_content', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sub_step_id'),
    schema='qa_test'
    )
    op.create_table('test_cases',
    sa.Column('test_case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_sheet_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('test_case_id'),
    schema='qa_test'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases', schema='qa_test')
    op.drop_table('sub_step', schema='qa_test')
    op.drop_table('step', schema='qa_test')
    op.drop_table('project', schema='qa_test')
    op.drop_table('generated_script', schema='qa_test')
    op.drop_table('case_sheet', schema='qa_test')
    op.drop_table('case_file', schema='qa_test')
    # ### end Alembic commands ###
