"""add new models

Revision ID: ed28429e90fc
Revises: 0693326c310b
Create Date: 2025-11-16 20:44:15.671402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed28429e90fc'
down_revision: Union[str, Sequence[str], None] = '0693326c310b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('case_file',
    # sa.Column('case_file_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('project_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('file_path', sa.String(length=1024), nullable=True),
    # sa.Column('login_info_id', sa.Integer(), nullable=True),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('case_file_id'),
    # schema='qa_test'
    # )
    # op.create_table('case_sheet',
    # sa.Column('case_sheet_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('case_file_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('case_sheet_id'),
    # schema='qa_test'
    # )
    # op.create_table('generated_script',
    # sa.Column('generated_script_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('sub_step_id', sa.Integer(), nullable=False),
    # sa.Column('script_content', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('generated_script_id'),
    # sa.UniqueConstraint('sub_step_id'),
    # schema='qa_test'
    # )
    op.create_table('knowledge_file',
    sa.Column('knowledge_file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('knowledge_file_id'),
    schema='qa_test'
    )
    op.create_table('login_info',
    sa.Column('login_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('web_url', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('login_info_id'),
    schema='qa_test'
    )
    # op.create_table('project',
    # sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('created_by_id', sa.Integer(), nullable=True),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.PrimaryKeyConstraint('project_id'),
    # schema='qa_test'
    # )
    op.create_table('screenshot',
    sa.Column('screenshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_script_id', sa.Integer(), nullable=False),
    sa.Column('screenshot_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('screenshot_id'),
    schema='qa_test'
    )
    # op.create_table('step',
    # sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('test_case_id', sa.Integer(), nullable=False),
    # sa.Column('project_id', sa.Integer(), nullable=True),
    # sa.Column('step_order', sa.Integer(), nullable=True),
    # sa.Column('action', sa.Text(), nullable=True),
    # sa.Column('expected_result', sa.Text(), nullable=True),
    # sa.Column('comment', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('step_id'),
    # schema='qa_test'
    # )
    # op.create_table('sub_step',
    # sa.Column('sub_step_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('step_id', sa.Integer(), nullable=False),
    # sa.Column('sub_step_order', sa.Integer(), nullable=False),
    # sa.Column('sub_step_content', sa.Text(), nullable=True),
    # sa.Column('expected_result', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('sub_step_id'),
    # schema='qa_test'
    # )
    # op.create_table('test_cases',
    # sa.Column('test_case_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('case_sheet_id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('test_case_id'),
    # schema='qa_test'
    # )
    op.create_table('test_result',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('result_id'),
    schema='qa_test'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('verification_code', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='qa_test'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='qa_test')
    op.drop_table('test_result', schema='qa_test')
    op.drop_table('test_cases', schema='qa_test')
    op.drop_table('sub_step', schema='qa_test')
    op.drop_table('step', schema='qa_test')
    op.drop_table('screenshot', schema='qa_test')
    op.drop_table('project', schema='qa_test')
    op.drop_table('login_info', schema='qa_test')
    op.drop_table('knowledge_file', schema='qa_test')
    op.drop_table('generated_script', schema='qa_test')
    op.drop_table('case_sheet', schema='qa_test')
    op.drop_table('case_file', schema='qa_test')
    # ### end Alembic commands ###
